-- AEVON KNOWLEDGE BASE — Supabase setup
-- Run this once in Supabase Dashboard > SQL Editor.
-- IMPORTANT: Never put your service_role key or Discord Client Secret in GitHub.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Discord user',
  avatar_url text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  icon text default '📁',
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tags (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  emoji text default '🏷️',
  created_at timestamptz not null default now()
);

create table if not exists public.articles (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  excerpt text,
  content_html text not null default '',
  keywords text default '',
  category_id uuid references public.categories(id) on delete set null,
  author_id uuid references public.profiles(id) on delete set null,
  status text not null default 'draft' check(status in ('draft','published')),
  pinned boolean not null default false,
  featured boolean not null default false,
  allow_comments boolean not null default true,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.article_tags (
  article_id uuid references public.articles(id) on delete cascade,
  tag_id uuid references public.tags(id) on delete cascade,
  primary key(article_id,tag_id)
);

create table if not exists public.article_likes (
  article_id uuid references public.articles(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(article_id,user_id)
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 800),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.article_views (
  id bigint generated by default as identity primary key,
  article_id uuid not null references public.articles(id) on delete cascade,
  viewer_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  term text not null check(char_length(term) between 2 and 100),
  user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_articles_status_published on public.articles(status,published_at desc);
create index if not exists idx_comments_article on public.comments(article_id,created_at desc);
create index if not exists idx_search_term on public.search_events(lower(term));
create index if not exists idx_views_article on public.article_views(article_id);

-- Keep updated_at accurate.
create or replace function public.touch_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists articles_touch_updated on public.articles;
create trigger articles_touch_updated before update on public.articles for each row execute function public.touch_updated_at();

-- Automatically create a safe public profile after Discord OAuth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles(id,display_name,avatar_url)
  values(
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name',new.raw_user_meta_data->>'user_name','Discord user'),
    coalesce(new.raw_user_meta_data->>'avatar_url',new.raw_user_meta_data->>'picture')
  )
  on conflict(id) do update set
    display_name=excluded.display_name,
    avatar_url=excluded.avatar_url;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of raw_user_meta_data on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = ''
as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') $$;

-- Enforce max 3 comments per account, per article, in rolling 24 hours.
create or replace function public.enforce_comment_limit()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare n int;
begin
  if new.user_id <> auth.uid() then raise exception 'Invalid user'; end if;
  select count(*) into n from public.comments
  where article_id=new.article_id and user_id=auth.uid() and created_at > now()-interval '24 hours';
  if n >= 3 then raise exception 'COMMENT_LIMIT: Maximum 3 comments per article every 24 hours'; end if;
  return new;
end $$;
drop trigger if exists comments_limit on public.comments;
create trigger comments_limit before insert on public.comments for each row execute function public.enforce_comment_limit();

-- Public helper functions for analytics. They reveal no private data.
create or replace function public.record_search(p_term text)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
  if char_length(trim(p_term)) between 2 and 100 then
    insert into public.search_events(term,user_id) values(lower(trim(p_term)),auth.uid());
  end if;
end $$;

create or replace function public.record_article_view(p_article_id uuid)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
  if exists(select 1 from public.articles where id=p_article_id and status='published') then
    insert into public.article_views(article_id) values(p_article_id);
  end if;
end $$;

create or replace view public.popular_searches
with (security_invoker = true)
as
select lower(term) as term,count(*)::bigint as searches
from public.search_events
where created_at > now()-interval '30 days'
group by lower(term)
order by searches desc;

-- RLS
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.tags enable row level security;
alter table public.articles enable row level security;
alter table public.article_tags enable row level security;
alter table public.article_likes enable row level security;
alter table public.comments enable row level security;
alter table public.article_views enable row level security;
alter table public.search_events enable row level security;

-- Profiles: public profile fields readable; users cannot grant themselves roles.
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select using(true);

-- Categories/tags: everyone reads, admin writes.
drop policy if exists "categories read" on public.categories;
create policy "categories read" on public.categories for select using(true);
drop policy if exists "categories admin insert" on public.categories;
create policy "categories admin insert" on public.categories for insert to authenticated with check(public.is_admin());
drop policy if exists "categories admin update" on public.categories;
create policy "categories admin update" on public.categories for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "categories admin delete" on public.categories;
create policy "categories admin delete" on public.categories for delete to authenticated using(public.is_admin());

drop policy if exists "tags read" on public.tags;
create policy "tags read" on public.tags for select using(true);
drop policy if exists "tags admin insert" on public.tags;
create policy "tags admin insert" on public.tags for insert to authenticated with check(public.is_admin());
drop policy if exists "tags admin update" on public.tags;
create policy "tags admin update" on public.tags for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "tags admin delete" on public.tags;
create policy "tags admin delete" on public.tags for delete to authenticated using(public.is_admin());

-- Published articles public; admins see/write everything.
drop policy if exists "published articles read" on public.articles;
create policy "published articles read" on public.articles for select using(status='published' or public.is_admin());
drop policy if exists "articles admin insert" on public.articles;
create policy "articles admin insert" on public.articles for insert to authenticated with check(public.is_admin() and author_id=auth.uid());
drop policy if exists "articles admin update" on public.articles;
create policy "articles admin update" on public.articles for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "articles admin delete" on public.articles;
create policy "articles admin delete" on public.articles for delete to authenticated using(public.is_admin());

drop policy if exists "article tags read" on public.article_tags;
create policy "article tags read" on public.article_tags for select using(exists(select 1 from public.articles a where a.id=article_id and (a.status='published' or public.is_admin())));
drop policy if exists "article tags admin insert" on public.article_tags;
create policy "article tags admin insert" on public.article_tags for insert to authenticated with check(public.is_admin());
drop policy if exists "article tags admin delete" on public.article_tags;
create policy "article tags admin delete" on public.article_tags for delete to authenticated using(public.is_admin());

-- Likes require Discord-authenticated user and must belong to that user.
drop policy if exists "likes read" on public.article_likes;
create policy "likes read" on public.article_likes for select using(true);
drop policy if exists "likes own insert" on public.article_likes;
create policy "likes own insert" on public.article_likes for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "likes own delete" on public.article_likes;
create policy "likes own delete" on public.article_likes for delete to authenticated using(user_id=auth.uid());

-- Comments: public sees non-hidden; owner can insert own; admin moderates.
drop policy if exists "comments read" on public.comments;
create policy "comments read" on public.comments for select using(not is_hidden or public.is_admin());
drop policy if exists "comments own insert" on public.comments;
create policy "comments own insert" on public.comments for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from public.articles a where a.id=article_id and a.status='published' and a.allow_comments));
drop policy if exists "comments admin update" on public.comments;
create policy "comments admin update" on public.comments for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "comments admin delete" on public.comments;
create policy "comments admin delete" on public.comments for delete to authenticated using(public.is_admin());

-- Analytics tables are not directly writable/readable from browser.
-- RPCs above handle inserts. Admin may read analytics later if desired.
drop policy if exists "views admin read" on public.article_views;
create policy "views admin read" on public.article_views for select to authenticated using(public.is_admin());
drop policy if exists "search admin read" on public.search_events;
create policy "search admin read" on public.search_events for select to authenticated using(public.is_admin());

-- API privileges (RLS still applies).
grant usage on schema public to anon,authenticated;
grant select on public.profiles,public.categories,public.tags,public.articles,public.article_tags,public.article_likes,public.comments,public.popular_searches to anon,authenticated;
grant insert,update,delete on public.categories,public.tags,public.articles,public.article_tags,public.comments to authenticated;
grant insert,delete on public.article_likes to authenticated;
grant select on public.article_views,public.search_events to authenticated;
grant execute on function public.is_admin() to anon,authenticated;
grant execute on function public.record_search(text) to anon,authenticated;
grant execute on function public.record_article_view(uuid) to anon,authenticated;

-- Storage bucket for article screenshots. Public read, ADMIN-ONLY writes.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('article-images','article-images',true,5242880,array['image/png','image/jpeg','image/webp','image/gif'])
on conflict(id) do update set public=true,file_size_limit=5242880,allowed_mime_types=array['image/png','image/jpeg','image/webp','image/gif'];

drop policy if exists "article images admin insert" on storage.objects;
create policy "article images admin insert" on storage.objects for insert to authenticated
with check(bucket_id='article-images' and public.is_admin());
drop policy if exists "article images admin update" on storage.objects;
create policy "article images admin update" on storage.objects for update to authenticated
using(bucket_id='article-images' and public.is_admin()) with check(bucket_id='article-images' and public.is_admin());
drop policy if exists "article images admin delete" on storage.objects;
create policy "article images admin delete" on storage.objects for delete to authenticated
using(bucket_id='article-images' and public.is_admin());

-- Starter content
insert into public.categories(name,slug,icon,sort_order) values
('Getting Started','getting-started','🚀',1),
('Server Guides','server-guides','📖',2),
('Support','support','🤝',3),
('Troubleshooting','troubleshooting','🛠️',4)
on conflict do nothing;

insert into public.tags(name,slug,emoji) values
('Support Tip','support-tip','🤝'),
('Helpful Tip','helpful-tip','💡'),
('Important','important','⚠️'),
('Guide','guide','📖'),
('Troubleshooting','troubleshooting','🛠️'),
('Gameplay','gameplay','🎮'),
('Economy','economy','💰'),
('PvP','pvp','⚔️'),
('Event','event','🏆'),
('Plugin','plugin','🧩'),
('New','new','🆕')
on conflict do nothing;

-- AFTER your first Discord sign-in, promote ONLY your account using its UUID:
-- update public.profiles set role='admin' where id='PASTE-YOUR-AUTH-USER-UUID-HERE';
-- Find your UUID at: Supabase Dashboard > Authentication > Users
